name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch
  pull_request:
    branches:
      - main  # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Set this to the node version you need

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build  # Your build script that generates output in /docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
